name: rubric
description: "A drag and drop editor built in flutter for creatings simple interactive lessons."
version: 0.0.2
homepage:

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  chewie: ^1.10.0
  
  file_picker: ^10.2.0
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  uuid: ^4.5.1
  video_player: ^2.9.2
  web: ^1.1.1
  youtube_parser: ^2.1.4
  youtube_player_iframe: ">=5.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  freezed: ^2.5.8
  json_serializable: ^6.9.3

flutter:
