name: rubric
description: "A drag and drop editor built in flutter for creatings simple interactive lessons."
version: 0.0.2
homepage:

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  chewie: ^1.10.0
  file_picker: ">=10.0.0"
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  video_player: ^2.9.2
  web: ^1.1.1
  youtube_parser: ^2.1.4
  youtube_player_iframe: ">=5.0.0"
  html: ^0.15.6
  flutter_widget_from_html: ^0.17.1
  internet_file: ^1.3.0
  http: ^1.6.0
  pdfrx: ^2.2.24

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.15
  custom_lint: ^0.8.0
  json_serializable: ^6.9.0
  freezed: ^3.0.6
  envied_generator: ^1.1.1
  mocktail: ^1.0.4
  firebase_auth_platform_interface: ^8.1.1
  firebase_core_platform_interface: ^6.0.0
  plugin_platform_interface: ^2.1.8
  analyzer: ^8.1.1
  analyzer_plugin: ^0.13.7

flutter:
